### ISSUE TITLE
ERROR: manifest for ioiobzit/nelson.mon:0.0.2 not found

### ISSUE THREAD

**Issue by helxsz** [ioiobzit/iota-nelson-node#1]
I am running the node on the digitialocean server.

> Pulling nelson.mon (ioiobzit/nelson.mon:0.0.2)...
> ERROR: manifest for ioiobzit/nelson.mon:0.0.2 not found

how to solve the issue?

**Comment by Dries-Vandenneucker** [comment]
Same here!

**Comment by ioiobzit** [comment]
Solved it, tag was not pushed correctly. Please try again :)

**Comment by Dries-Vandenneucker** [comment]
That's it! Thanks!
