### ISSUE TITLE
Grafana No data points and N/A

### ISSUE THREAD

**Issue by oyren** [ioiobzit/iota-nelson-node#16]
I followed the instruction for installation, but in Grafana i see "No data points" on most entries.

In the Row IRI Node Stats (Lastest Milestone and so on)  i can only see N/A.

Grafana Log shows:
t=2018-02-18T23:37:44+0100 lvl=eror msg="provisioned dashboard json files cannot contain id" logger=provisioning.dashboard type=file name=IOTA0mq

https://imgur.com/a/0bcQy
https://imgur.com/a/6Xj84

**Comment by stereu** [comment]
Same here, iota-prom-exporter seems to be the problem. It's restarting over and over.

**Comment by oyren** [comment]
I'm back on a non docker setup.
At first I had the same mistake issue but a git pull on https://github.com/crholliday/iota-prom-exporter helped.

**Comment by ioiobzit** [comment]
Probalbly the docker-container is not up-to-date yet.

**Comment by ioiobzit** [comment]
Solved with the latests image and this PR on my repo:
https://github.com/ioiobzit/iota-nelson-node/pull/18
