### ISSUE TITLE
Firewall exposed

### ISSUE THREAD

**Issue by oyren** [ioiobzit/iota-nelson-node#17]
If i am right port 9090 and 9100 should't be open for public. But they are.

I suppose this happens due https://askubuntu.com/questions/652556/uncomplicated-firewall-ufw-is-not-blocking-anything-when-using-docker

**Comment by ioiobzit** [comment]
Changed the ports for prometheus to ```expose``` instead of ```ports``` now it should work as intended and ports should be closed to the public.
