### ISSUE TITLE
Prometheus: "Opening storage failed open DB in /data: open /data/724784799: permission denied

### ISSUE THREAD

**Issue by firesurf** [ioiobzit/iota-nelson-node#22]
I followed everything in your readme, but get this:

> level=info ts=2018-03-09T13:22:17.96195575Z caller=main.go:220 msg="Starting Prometheus" version="(version=2.2.0, branch=HEAD, revision=f63e7db4cbdb616337ca877b306b9b96f7f4e381)"
> level=info ts=2018-03-09T13:22:17.962102139Z caller=main.go:221 build_context="(go=go1.10, user=root@52af9f66ce71, date=20180308-16:40:42)"
> level=info ts=2018-03-09T13:22:17.962175703Z caller=main.go:222 host_details="(Linux 3.10.102 #15254 SMP Fri Jan 26 06:46:44 CST 2018 x86_64 prometheus (none))"
> level=info ts=2018-03-09T13:22:17.962219253Z caller=main.go:223 fd_limits="(soft=524288, hard=1048576)"
> level=info ts=2018-03-09T13:22:18.074241532Z caller=main.go:504 msg="Starting TSDB ..."
> level=info ts=2018-03-09T13:22:18.074989904Z caller=main.go:398 msg="Stopping scrape discovery manager..."
> level=info ts=2018-03-09T13:22:18.075200182Z caller=main.go:411 msg="Stopping notify discovery manager..."
> level=info ts=2018-03-09T13:22:18.07525607Z caller=main.go:432 msg="Stopping scrape manager..."
> level=info ts=2018-03-09T13:22:18.075304196Z caller=manager.go:460 component="rule manager" msg="Stopping rule manager..."
> level=info ts=2018-03-09T13:22:18.075384659Z caller=manager.go:466 component="rule manager" msg="Rule manager stopped"
> level=info ts=2018-03-09T13:22:18.075443998Z caller=notifier.go:512 component=notifier msg="Stopping notification manager..."
> level=info ts=2018-03-09T13:22:18.075539511Z caller=web.go:382 component=web msg="Start listening for connections" address=0.0.0.0:9090
> level=info ts=2018-03-09T13:22:18.084396889Z caller=main.go:394 msg="Scrape discovery manager stopped"
> level=info ts=2018-03-09T13:22:18.084607142Z caller=main.go:407 msg="Notify discovery manager stopped"
> level=info ts=2018-03-09T13:22:18.084679155Z caller=main.go:426 msg="Scrape manager stopped"
> level=info ts=2018-03-09T13:22:18.084744731Z caller=main.go:573 msg="Notifier manager stopped"
> level=error ts=2018-03-09T13:22:18.084799269Z caller=main.go:582 err="Opening storage failed open DB in /data: open /data/724784799: permission denied"
> level=info ts=2018-03-09T13:22:18.084898183Z caller=main.go:584 msg="See you next time!"

Thank you

**Comment by firesurf** [comment]
Tried this multiple times: 

> For the Grafana Dashboard to work, first we have to fix Prometheus. See the documentation here. Please go to ./volumes/prometheus and execute the following command

sudo chown nobody. data

Restart the Prometheus container

docker-compose restart prometheus

**Comment by henningvs** [comment]
What does ls -l or ll show when you look at the directory?

It should look like this:
```
root@vm:~/github/ioiobzit/iota-nelson-node# ll volumes/prometheus/
total 16
drwxr-xr-x 3 root   root    4096 Mar  9 15:37 ./
drwxr-xr-x 8 root   root    4096 Mar  9 15:34 ../
drwxr-xr-x 7 nobody nogroup 4096 Mar 10 15:22 data/
-rw-r--r-- 1 root   root    1201 Mar  9 15:34 prometheus.yml
```

**Comment by firesurf** [comment]
```
drwxrwxrwx+ 1   1000   1000   36 Mar  9 12:22 .
drwxrwxrwx+ 1   1000   1000   70 Mar  9 12:01 ..
drwxrwxrwx+ 1 nobody nobody    0 Mar  9 12:22 data
-rwxrwxrwx+ 1   1000   1000 1201 Feb 26 12:26 prometheus.yml
```
Looks a little differnt. It's on a Synology NAS and I used another docker tutorial for it.

**Comment by ioiobzit** [comment]
sometimes docker does not like folders mounted over nas.
Had the same issue with a redmine container.

Please first try to mount a local path.

Thank you.
