### ISSUE TITLE
IRI remote API access security problem

### ISSUE THREAD

**Issue by zoran** [ioiobzit/iota-nelson-node#24]
`REMOTE_LIMIT_API = "interruptAttachingToTangle, attachToTangle"` in the `iota.ini`

means that the commands are executable for the internet which is problematic:

`removeNeighbors, addNeighbors, getNeighbors,  setApiRateLimit`

**Comment by ioiobzit** [comment]
I know about this, that is why everyone should set this limits according to his necessities and responsability.
The Read.me states:

> Remote API limits
>
>At this point NO API limits are now default!
>
>Following API limits are to be set as best practice (see iota.partners site or discussions on discord), but are not enabled as explained in the following table

**Comment by mndhkr** [comment]
Is it really mandatory to have this limits?
At worst, what can happen with no limits?

Thank you
