### ISSUE TITLE
Step problem

### ISSUE THREAD

**Issue by nerminao** [ioiobzit/iota-nelson-node#27]
Hello,
I need help to solve a problem. I was trying to run command docker-compose up -d. I followed all steps from this page https://github.com/ioiobzit/iota-nelson-node. All this is done on the server and attached you can find picture of problem that occurs.  Can you help me solve this? Thank you. 
Best regards,
Nermina
![pokit_3416a75f4cea9109507cacd8e2f2aefc](https://user-images.githubusercontent.com/38084458/38330533-2a7e098a-3851-11e8-88e6-6b2c1bee39fc.jpg)

**Comment by ioiobzit** [comment]
Hi, I've removed nelson.mon.
Please pull and try again.

**Comment by nerminao** [comment]
Thank you so much!
