### ISSUE TITLE
/etc/localtime unavailable on Windows

### ISSUE THREAD

**Issue by mndhkr** [ioiobzit/iota-nelson-node#29]
Creating iota_iri ...
Creating iota_nelson.gui ...
Creating iota_prom-nodeexp ... error
Creating iota_prom-iotaexp ...
Creating iota_nelson.cli   ...
Creating iota_field.cli    ...

Creating iota_nelson.gui   ... done
h'
Creating iota_iri          ... error
ERROR: for iota_nelson.cli  Cannot create container for service nelson.cli: b'Mount denied:\nThe source path "\\\\etc\\\\localtime:/etc/localtime"\nis not a valid Creating iota_field.cli    ... error

ERROR: for iota_field.cli  Cannot create container for service field.cli: b'Mount denied:\nThe source path "\\\\etc\\\\localtime:/etc/localtime"\nis not a valid WiCreating iota_prom-iotaexp ... error

ERROR: for iota_iri  Cannot create container for service iota: b'Mount denied:\nThe source path "\\\\etc\\\\localtime:/etc/localtime"\nis not a valid Windows path'

ERROR: for iota_prom-iotaexp  Cannot create container for service iota-prom-exporter: b'Mount denied:\nThe source path "\\\\etc\\\\localtime:/etc/localtime"\nis not a valid Windows path'

ERROR: for node-exporter  Cannot create container for service node-exporter: b'Mount denied:\nThe source path "\\\\proc:/host/proc"\nis not a valid Windows path'

ERROR: for nelson.cli  Cannot create container for service nelson.cli: b'Mount denied:\nThe source path "\\\\etc\\\\localtime:/etc/localtime"\nis not a valid Windows path'

ERROR: for field.cli  Cannot create container for service field.cli: b'Mount denied:\nThe source path "\\\\etc\\\\localtime:/etc/localtime"\nis not a valid Windows path'

ERROR: for iota  Cannot create container for service iota: b'Mount denied:\nThe source path "\\\\etc\\\\localtime:/etc/localtime"\nis not a valid Windows path'

ERROR: for iota-prom-exporter  Cannot create container for service iota-prom-exporter: b'Mount denied:\nThe source path "\\\\etc\\\\localtime:/etc/localtime"\nis not a valid Windows path'
Encountered errors while bringing up the project.

**Comment by ioiobzit** [comment]
Please comment following lines:

```
14
38
61
74
94
108
125
```
