### ISSUE TITLE
connect to IOTA Wallet (BETA) for Android

### ISSUE THREAD

**Issue by illBeRespawned** [ioiobzit/iota-nelson-node#3]
I'm trying to connect this node to the IOTA Wallet (BETA) for Android (https://play.google.com/store/apps/details?id=org.iota.wallet)

App reports that this command is not available on the node.

I've been trying to find the option to enable this and per the iota help it should be the "remote" flag.

But as far as I can tell this flag is set true in the used iota.ini in the repo.

Any idea why that might be?

**Comment by ioiobzit** [comment]
What is your docker host IP on the internal network and what IP:port are you trying to connect to?

**Comment by illBeRespawned** [comment]
thanks for the fast response

I tried
104.40.238.69:14600
and
104.40.238.69:15600

same results for both

**Comment by ioiobzit** [comment]
Hi,

to access your IRI node with the wallet, you need to set the API port 14265.

The listed ports 14600 and 15600 are for other nodes to connect to yours, over UDP and TCP respectively.

Let me know if there are other issues.

All the best,
Antonio

**Comment by illBeRespawned** [comment]
also tried it with 104.40.238.69:14265
same result

**Comment by ioiobzit** [comment]
Hello,

I could connect to my test VPS with the following settings:

Node protocol: `http`
Node ip: `MY.IP.ADD.RESS`
Node port: `14265`

Please verify that your port is open.

All the best.
