### ISSUE TITLE
IOTA full node cannot fully synchronized

### ISSUE THREAD

**Issue by godleon** [ioiobzit/iota-nelson-node#4]
I just followed the usage section to deploy IOTA full node on my computer with Ubuntu 16.04, but I found the node never fully synchronized. When I tried to get node information from API, the number of **latestSolidSubtangleMilestoneIndex** and **latestMilestoneIndex** is never consistent. **latestMilestoneIndex** is constantly increasing, but  **latestSolidSubtangleMilestoneIndex** stuck.

Is there any additional configuration I should make before doing `docker-compose up -d`?

Thanks!

**Comment by ioiobzit** [comment]
Hello,
that is a common issue for IOTA nodes so far, mine is up 2 days and three hours and went from 243000 (last snapshot) to 243076.
 [Try following solution](https://github.com/iotaledger/iri/issues/375).

Please be aware to always have a maximum of 7 neighbors combined between Nelson and IRI nodes.

Try again with the new iota/iota.ini and nelson/config.ini committed today.

**Comment by godleon** [comment]
Hi ioiobzit, 
I've tried your new commit but it didn't work because of the modification of **IRIHostname** from `iota` to `localhost`. Once I made the modification, Nelson cannot connect to IRI anymore. I think the root cause of this problem is that IRI and Nelson containers are not in the same network namespace. 
Could you please check this again? Thanks!

**Comment by ioiobzit** [comment]
Hi,

I've set the IRIHostname back to iota.
Now it should work normally. After four days my node is at 243458 of 316640.
It should have nothing to do do with the network namespace, since if you enter the nelson.cli container you can ping the iota hostname without errors.

**Comment by ioiobzit** [comment]
Solved with this workaround:

https://www.reddit.com/r/Iota/comments/7ittd7/full_node_stuck_at_a_milestone_and_wont_fully_sync/

Waiting for the IRI team to solve it definitely:
https://github.com/iotaledger/iri/issues/428
