### ISSUE TITLE
Issues reducing cpu usages

### ISSUE THREAD

**Issue by codepleb** [ioiobzit/iota-nelson-node#5]
I tried to reduce the CPU usage, by adding some lines to the docker-compose.yml:

`
deploy:
  resources:
    limits:
      cpus: '0.3'
`

To reduce the consumed cpu resources (because otherwise, my home server is completely useless in all other tasks he is doing).

It doesn't work, apparently because the "version" at the top is outdated (2 and not 3). I am a docker beginner, but could you probably come up with a solution to make that possible?

GREAT work btw! I love this approach.

Suggestion: I would explain, how we can "minimalize" this, to give the node the max amount of resources. The dashboard and whatever fancy stuff won't be needed by anyone I guess. I myself just removed the entries from the docker-compose.yml file, but not sure if that works.

**Comment by panromir** [comment]
https://docs.docker.com/compose/compose-file/compose-file-v2/#restart

You can refer to this for now. "cpus" was added in 2.2, you will have to use CPU quota.

**Comment by codepleb** [comment]
This works, thank you.

For everyone interested, open the docker-compose.yml file and change accordingly, to limit CPU usage to 50%:

`
...................
  iota:
    image: iotaledger/iri:latest
    container_name: iota
    hostname: iota
    cpu_quota: 50000
    restart: unless-stopped
    volumes:
................
`
