### ISSUE TITLE
nelson.gui unable to connect to iri

### ISSUE THREAD

**Issue by idodev** [ioiobzit/iota-nelson-node#6]
Firstly, before anything else. This project is amazing! Had started grafting a docker solution (feeble in comparison) and stumbled over this. Thank you!

To the issue. The nelson.gui is erroring with `IRI not ready on localhost:14265, retrying...` when checking the docker logs.
Attached and tested `telnet localhost 14265` and its unable to connect. Running curl against `http://localhost:14265` from the host returns successfully.

Any thoughts? 

(Edit: should this be trying to connect to iota:14265 instead?)

**Comment by ioiobzit** [comment]
Hi,

than you for your comment!
True, I had the original romansemko/nelson.gui in my docker-compose file. To make it work I made a custom one.
Please clone the repo again and try, it should work now :)
Let me know should you have other issues.

All the best,
Antonio

**Comment by idodev** [comment]
Excellent, that did it! Thanks for the fix.
