### ISSUE TITLE
High value configured for MAX_PEERS

### ISSUE THREAD

**Issue by Wollac** [ioiobzit/iota-nelson-node#7]
Is there a particular reason why you chose a value of 7 for `MAX_PEERS` in the IRI configuration instead of the default of 0?
When run in testnet, this allows 7 additional neighbors to connect without having them configured as neighbors. Apparently, this has no influence for `TESTNET = false`, but it still might be favorable to set it to 0 or remove it from iota.ini and use the default.

**Comment by ioiobzit** [comment]
Hi,

thank you for the question.
From what I understood, the ideal and maximum number of nodes so far is 7, no more, no less.

> Come-from-Beyond @here To ease the syncing issue reduce number of your neighbors. 7 should be the hard cap even if it's your mother asking to add her as the 8th neighbor. Use 3 neighbors if you are sure that they won't remove you without informing, use 5 if you are not sure in that. Thread in #nodesharingDec 4th at 9:54 AM

The iotaledger/iri table says:

>  Limit the number of max accepted peers. Default is set to 0 (mutual tethering)

Therefore I was limiting the maximum number of peers.

Could you please show me where to find the detail where it says that it has no influence with `TESTNET = false`?

Cheers.

**Comment by Wollac** [comment]
As far as I understood, `MAX_PEERS` does not limit the number of (configured) neighbors you can add, it only limits the number of peers that can connect to the node without having them added as neighbors. I.e. `MAX_PEERS==0` means mutual tethering only, so A needs to have B added, and B needs to have A adden. I guess this is how the description in the official iotaledger/iri table should be interpreted and why the default is 0.
I tried to check the code and found the following:
https://github.com/iotaledger/iri/blob/63d232d2932cc15ac7499ed579b3d1587c3a9dbe/src/main/java/com/iota/iri/network/Node.java#L309
You have there, that if the received data is not from a neighbor and you are in TESTNET and you are bellow MAX_PEERS, add a non-tethered neighbor.

The configured neighbors are parsed here, without checking `MAX_PEERS` at all:
https://github.com/iotaledger/iri/blob/63d232d2932cc15ac7499ed579b3d1587c3a9dbe/src/main/java/com/iota/iri/network/Node.java#L700

**Comment by ioiobzit** [comment]
Thank you for your contribution!
I'll change the iota.ini file.
