### ISSUE TITLE
nelson.cli cannot connect

### ISSUE THREAD

**Issue by arnold-maderthaner** [ioiobzit/iota-nelson-node#8]
Hi !

Just tried your project and I have an issue with nelson.cli:

12:36:44 PM.671	16600::IRI   IRI not ready on iota:14265, retrying...

If I do the following I get at least a respond from iri:
 root@mail:~/iota-nelson-node# docker exec -it nelson.cli /bin/sh
/ # wget http://iota:14265
Connecting to iota:14265 (172.18.0.7:14265)
wget: server returned error: HTTP/1.1 400 Bad Request

So IRI should be running and listening.

Also docker logs iota shows that iri is synching:
01/23 11:49:08.438 [main] INFO  com.iota.iri.IRI - IOTA Node initialised correctly.
01/23 11:49:18.111 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 0 , toReply = 0 / totalTransactions = 0

any idea what could be wrong ?

**Comment by ioiobzit** [comment]
Hi, can you please show me your volumes/iota/iota.ini?

Thanks

**Comment by ioiobzit** [comment]
Please tell me if problem persists.

Thank you
